# Spring configuration
spring:
  profiles:
    active: dev                           # env profile
    include:                              # including profiles
    - h2
    - redis
  h2.console.enabled: true                # enabling H2 Console: /h2-console
  datasource:
    platform: h2                          # database platform
    url: jdbc:h2:mem:testdb
  redis:
    host: localhost
    port: 6379
  session:
    store-type: redis                     # redis, jdbc, none etc.
  flyway:                                 # flyway
    schemas:
    - PUBLIC
    
# Server
server:
  servlet:
    session:
      timeout: 5                          # seconds

# Logging
logging:
  level:
    root: ERROR
    org.springframework: INFO
    bright.zheng: INFO
  pattern:
    console: "==> [%p] %c{1}(%L) - %m%n"

# Actuator Configuration
management:
  endpoints:
    enabled-by-default: false
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
    metrics:
      enabled: true
