# Spring configuration
spring:
  profiles:
    active: qa
    include:
    - mysql
    - redis
  h2.console.enabled: false

# Logging
logging:
  level:
    root: ERROR
    org.springframework: INFO
    bright.zheng: INFO
  pattern:
    console: "==> [%p] %c{1}(%L) - %m%n"


# Actuator Configuration
management:
  endpoints:
    enabled-by-default: false
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
    metrics:
      enabled: true
